### ISSUE TITLE
Should be able to add packages in the action `with:`

### ISSUE THREAD

**Issue by mxcl** [teaxyz/setup#133]
eg.

```yaml
- uses: teaxyz/setup@v0
  with:
    deno.land: ^1.30
    nodes.org: ^19
```
